version: '3'
services:
  nginx-php72:
    build:
      context: ./src/
      dockerfile: Dockerfile
    restart: always
    ports:
    - "${NGINX_HTTP_HOST_PORT}:80"
    volumes:
    - ${SOURCE_DIR}:/opt/case
    #extra_hosts:
    #links:
    networks:
      default:
        ipv4_address: 10.10.0.1
    tty: true
    cap_add:
    - SYS_PTRACE
networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.0.0/16